import {
  createHash,
  createHmac,
  randomBytes,
  timingSafeEqual,
} from "node:crypto";

/* =========================================================
   CONSTANTS
========================================================= */

const MANAGE_TOKEN_VERSION =
  "m1";

/* =========================================================
   HELPERS
========================================================= */

function hashToken(
  token: string,
): string {
  return createHash(
    "sha256",
  )
    .update(
      token,
      "utf8",
    )
    .digest(
      "hex",
    );
}

function safeStringEqual(
  left: string,
  right: string,
): boolean {
  const leftBuffer =
    Buffer.from(
      left,
      "utf8",
    );

  const rightBuffer =
    Buffer.from(
      right,
      "utf8",
    );

  if (
    leftBuffer.length !==
    rightBuffer.length
  ) {
    return false;
  }

  return timingSafeEqual(
    leftBuffer,
    rightBuffer,
  );
}

function getBookingManageSecret(): string {
  const secret =
    process.env
      .BOOKING_MANAGE_SECRET
      ?.trim();

  if (!secret) {
    throw new Error(
      "BOOKING_MANAGE_SECRET is not configured.",
    );
  }

  if (
    secret.length <
    32
  ) {
    throw new Error(
      "BOOKING_MANAGE_SECRET is too short.",
    );
  }

  return secret;
}

/* =========================================================
   LEGACY / PRIMARY RANDOM TOKEN

   Used by the initial confirmation flow.

   DB stores only SHA-256(token).
========================================================= */

export function createBookingToken(): {
  token: string;
  tokenHash: string;
} {
  const token =
    randomBytes(
      32,
    ).toString(
      "base64url",
    );

  return {
    token,

    tokenHash:
      hashToken(
        token,
      ),
  };
}

export function verifyBookingToken(
  token: string,
  tokenHash: string,
): boolean {
  if (
    !token ||
    !tokenHash
  ) {
    return false;
  }

  const calculatedHash =
    hashToken(
      token,
    );

  return safeStringEqual(
    calculatedHash,
    tokenHash,
  );
}

/* =========================================================
   DERIVED MANAGE TOKEN

   This can be regenerated by the server later without
   storing the plaintext customer token.

   It is bound to:
   - booking ID
   - current cancelTokenHash
   - BOOKING_MANAGE_SECRET

   Changing/revoking cancelTokenHash automatically invalidates
   all derived manage links for the booking.
========================================================= */

export function createBookingManageToken({
  bookingId,
  tokenHash,
}: {
  bookingId: string;
  tokenHash: string;
}): string {
  const secret =
    getBookingManageSecret();

  const payload =
    [
      MANAGE_TOKEN_VERSION,
      bookingId,
      tokenHash,
    ].join(
      ":",
    );

  const signature =
    createHmac(
      "sha256",
      secret,
    )
      .update(
        payload,
        "utf8",
      )
      .digest(
        "base64url",
      );

  return `${MANAGE_TOKEN_VERSION}.${signature}`;
}

/* =========================================================
   UNIVERSAL BOOKING ACCESS VERIFICATION

   Accepts:
   1. existing random token from old/original emails
   2. derived signed token from reminder emails
========================================================= */

export function verifyBookingAccessToken({
  bookingId,
  token,
  tokenHash,
}: {
  bookingId: string;
  token: string;
  tokenHash: string;
}): boolean {
  if (
    !bookingId ||
    !token ||
    !tokenHash
  ) {
    return false;
  }

  /*
   * Existing confirmation emails continue working.
   */
  if (
    verifyBookingToken(
      token,
      tokenHash,
    )
  ) {
    return true;
  }

  if (
    !token.startsWith(
      `${MANAGE_TOKEN_VERSION}.`,
    )
  ) {
    return false;
  }

  let expectedToken:
    string;

  try {
    expectedToken =
      createBookingManageToken({
        bookingId,
        tokenHash,
      });
  } catch {
    return false;
  }

  return safeStringEqual(
    token,
    expectedToken,
  );
}